kind: Service
apiVersion: v1
metadata:
  name: anrehberger-deloitte
  labels:
    net.beedemo.deploy.type: workshop
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: anrehberger-deloitte
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: anrehberger-deloitte-staging
  labels:
    net.beedemo.deploy.type: workshop
spec:
  replicas: 1
  template:
    metadata:
      name: anrehberger-deloitte
      labels:
        net.beedemo.deploy.type: workshop
        app: anrehberger-deloitte
        env: staging
    spec:
      containers:
      - name: anrehberger-deloitte
        image: gcr.io/core-workshop/helloworld-nodejs:anrehberger-deloitte-1
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
        imagePullPolicy: Always
        ports:
        - name: public
          containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: anrehberger-deloitte
  labels:
    net.beedemo.deploy.type: workshop
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - http:
      paths:
      - path: /anrehberger-deloitte/?(.*)
        backend:
          serviceName: anrehberger-deloitte
          servicePort: 80
    host: staging.cb-sa.io
